-- Public contact-form submissions with staff-only review and status updates.
BEGIN;

CREATE TABLE public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL CHECK (char_length(trim(full_name)) BETWEEN 2 AND 120),
  phone TEXT NOT NULL CHECK (phone ~ '^\+?[0-9 ()-]{7,24}$'),
  email TEXT CHECK (email IS NULL OR email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$'),
  message TEXT NOT NULL CHECK (char_length(trim(message)) BETWEEN 5 AND 4000),
  status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.contact_messages FROM PUBLIC, anon, authenticated;
GRANT INSERT ON public.contact_messages TO anon, authenticated;
GRANT SELECT, UPDATE (status) ON public.contact_messages TO authenticated;

CREATE POLICY "public_insert_contact_messages"
  ON public.contact_messages FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "appointment_staff_read_contact_messages"
  ON public.contact_messages FOR SELECT TO authenticated
  USING ((SELECT public.is_appointment_staff()));

CREATE POLICY "appointment_staff_update_contact_message_status"
  ON public.contact_messages FOR UPDATE TO authenticated
  USING ((SELECT public.is_appointment_staff()))
  WITH CHECK ((SELECT public.is_appointment_staff()));

CREATE INDEX idx_contact_messages_status ON public.contact_messages (status);
CREATE INDEX idx_contact_messages_created_at ON public.contact_messages (created_at DESC);

COMMIT;
